# Generated by Django 4.2.1 on 2024-03-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeevent',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Art', 'Art'), ('Conference', 'Conference'), ('Cultural', 'Cultural'), ('Music', 'Music'), ('Other', 'Other'), ('Seminar', 'Seminar'), ('Social', 'Social'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Workshop', 'Workshop')], max_length=20),
        ),
        migrations.AlterField(
            model_name='collegeevent',
            name='image',
            field=models.ImageField(upload_to='event_images/'),
        ),
    ]
