# Generated by Django 4.2.1 on 2024-03-17 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_alter_collegeevent_category_alter_collegeevent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeevent',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
