# Generated by Django 4.2.1 on 2024-03-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_collegeevent_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeevent',
            name='participants',
        ),
    ]
