# Generated by Django 4.2.1 on 2024-03-17 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_remove_collegeevent_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeevent',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
