# Generated by Django 4.2.1 on 2023-12-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.CharField(default='278a04d906', max_length=10, unique=True),
        ),
    ]
