# Generated by Django 4.2.1 on 2023-12-17 10:10

from django.db import migrations, models
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_group_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.CharField(default=social.models.generate_unique_group_id, max_length=10, unique=True),
        ),
    ]
