# Generated by Django 4.2.1 on 2023-12-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_remove_post_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='group_post', to='social.group'),
        ),
    ]
