# Generated by Django 4.2.1 on 2024-03-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_post_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='groups', to='social.tag'),
        ),
    ]
