# Generated by Django 4.2.1 on 2024-03-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_tag_group_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='group',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
