# Generated by Django 4.2.1 on 2024-03-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_college_university_userprofile_github_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='university_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.college'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.university'),
        ),
    ]
